name: cnc-sig-action
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:  
jobs:
  build:
    runs-on: self-hosted
    permissions: write-all
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      
      #- name: Coverity Full Scan
      #  if: ${{ github.event_name != 'pull_request' }}
      #  uses: synopsys-sig/synopsys-action@v1.13.0
      #  with:
      #    coverity_url: https://synopsys-coverity-balwurk:8442/
      #    coverity_user: ${{ secrets.COVERITY_USER }}
      #    coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
      #    coverity_project_name: webgoatcli
      #    coverity_stream_name: webgoatcli
      #    coverity_local: true

      #- name: Run Cov-Format-Errors Command
      #  run: /home/azureuser/synopsys/cov-analysis/bin/cov-format-errors --dir /home/azureuser/actions-runner/_work/test/test/idir/ --json-output-v7 /home/azureuser/actions-runner/_work/test/test/idir/coverity-results.json
      #  shell: bash

      #- name: Create SARIF file
      #  run: node /home/azureuser/synopsys/cov-analysis/SARIF/cov-format-sarif-for-github.js --inputFile /home/azureuser/actions-runner/_work/test/test/idir/coverity-results.json --outputFile /home/azureuser/actions-runner/_work/test/test/idir/coverity-results_SARIF.json --githubUrl https://github.com --repoName testaccountcoverity/test --checkoutPath testaccountcoverity/test test/src 1212121212121212121212121212121212121212

      #- name: Upload SARIF to GitHub
      #  uses: github/codeql-action/upload-sarif@v3
      #  with:
      #    sarif_file: /home/azureuser/actions-runner/_work/test/test/idir/coverity-results_SARIF.json
      - name: test
        run: |
         COVERITY_TOOL_HOME=/home/azureuser/synopsys/cov-analysis     
          IDIR=$(find ${{ github.workspace }}/ -name idir)
          $COVERITY_TOOL_HOME/bin/cov-format-errors --dir "$IDIR" --json-output-v7 $IDIR/issues.json
          $COVERITY_TOOL_HOME/node/bin/node $COVERITY_TOOL_HOME/SARIF/cov-format-sarif-for-github.js --inputFile $IDIR/issues.json --outputFile $IDIR/results.json \
          --githubUrl ${{ github.server_url }} --repoName ${{ github.repository }} --checkoutPath ${{ github.repository }} ${{ github.workspace }}/src ${{ github.sha }}
       
        shell: bash
      
      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: /home/azureuser/actions-runner/_work/test/test/idir/results.json

 
